# syntax=docker/dockerfile:1

FROM golang:1.22 AS build-stage
WORKDIR /twohandlers
COPY go.mod go.sum ./
RUN go mod download
COPY ./ ./
RUN go build -o /build ./cmd/main.go

FROM build-stage AS run-test-stage
RUN go test -v ./...

FROM gcr.io/distroless/base-debian11 AS build-release-stage
WORKDIR /
COPY --from=build-stage /build /build
EXPOSE 3000
USER nonroot:nonroot
ENTRYPOINT ["/build"]
